[workspace]
authors = ["avcopan <avcopan@gmail.com>"]
channels = ["conda-forge"]
name = "cookiecutter-pixi-python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
clean = "rm -rf ../project_name"
build = "cookiecutter . --no-input -o .. && git init ../project_name"
test = { cmd = "pixi run hooks", cwd = "../project_name" }
init = { cmd = "pixi run init", cwd = "../project_name" }
version = { cmd = "pixi run bumpver show", cwd = "../project_name" }
license = { cmd = "cat LICENSE", cwd = "../project_name" }
readme = { cmd = "cat README.md", cwd = "../project_name" }

[tasks.all]
depends-on = [
    "clean",
    "build",
    "test",
    "init",
    "version",
    "readme",
    "license",
]

[dependencies]
cookiecutter = ">=2.6.0,<3"
