[workspace]
authors = ["avcopan <avcopan@gmail.com>"]
channels = ["conda-forge"]
name = "cookiecutter-pixi-python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
clean = "rm -r ../project_name || true"
build = "cookiecutter . --no-input -o .. && git init ../project_name"
test = { cmd = "pixi run hooks", cwd = "../project_name" }
all = { depends-on = ["clean", "build", "test"] }

[dependencies]
cookiecutter = ">=2.6.0,<3"
