[workspace]
authors = ["avcopan <avcopan@gmail.com>"]
channels = ["conda-forge"]
name = "cookiecutter-pixi-python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
clean = "rm -rf ../project_name"
build = "cookiecutter . --no-input -o .."
setup = { cmd = "pixi run setup", cwd = "../project_name" }
pre-commit = { cmd = "pixi run pre-commit", cwd = "../project_name" }
docs-build = { cmd = "pixi run docs-build", cwd = "../project_name" }
readme = { cmd = "cat README.md", cwd = "../project_name" }
license = { cmd = "cat LICENSE", cwd = "../project_name" }
version = { cmd = "pixi run bumpver show", cwd = "../project_name" }

[tasks.all]
depends-on = [
    "clean",
    "build",
    "setup",
    "pre-commit",
    "docs-build",
    "readme",
    "license",
    "version",
]

[dependencies]
cookiecutter = ">=2.6.0,<3"
