github_url = "https://github.com/{{cookiecutter.github_org_name}}/{{cookiecutter.package_name}}"

[version]
current = "0.0.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[file]]
src = "pixi.toml"
search = 'version = "{current_version}"'

[[file]]
src = "src/{{cookiecutter.package_name}}/__init__.py"
search = '__version__ = "{current_version}"'

[[before_commit]]
name = "Update changelog"
cmd = "pixi run changelog {new_version}"

[[before_commit]]
name = "Add changelog to commit"
cmd = "git add CHANGELOG.md"

[[before_commit]]
name = "Update lockfile"
cmd = "pixi lock"

[[before_commit]]
name = "Add lockfile to commit"
cmd = "git add pixi.lock"