name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initialize Pixi
        uses: prefix-dev/setup-pixi@v0.9.3

      - name: Run cookiecutter
        run: |
          mkdir build
          pixi run cookiecutter . --no-input -o ..

      - name: Test package
        run: |
          cd ../project_name
          pixi run echo Hi
