name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initialize Pixi
        uses: prefix-dev/setup-pixi@v0.9.3

      - name: Run cookiecutter
        run: pixi run build

      - name: Test package
        run: pixi run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ../project_name/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
